// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Urbanizze.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508213451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<int>("MensagemId")
                        .HasColumnType("int")
                        .HasColumnName("id_mensagem");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("MensagemId");

                    b.ToTable("ANEXO");
                });

            modelBuilder.Entity("Cidadao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("CIDADAO");
                });

            modelBuilder.Entity("Denuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonima")
                        .HasColumnType("bit")
                        .HasColumnName("anonima");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("CidadaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_cidadao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("id_departamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_funcionario");

                    b.Property<int>("StatusDenuncia")
                        .HasColumnType("int");

                    b.Property<int>("StatusDenunciaId")
                        .HasColumnType("int")
                        .HasColumnName("id_status_denuncia");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CidadaoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("DENUNCIA");
                });

            modelBuilder.Entity("Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<int>("PrefeituraCidadeId")
                        .HasColumnType("int")
                        .HasColumnName("id_prefeitura_cidade");

                    b.HasKey("Id");

                    b.HasIndex("PrefeituraCidadeId");

                    b.ToTable("DEPARTAMENTO");
                });

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("CidadaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_cidadao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("id_departamento");

                    b.HasKey("Id");

                    b.HasIndex("CidadaoId")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.ToTable("FUNCIONARIO");
                });

            modelBuilder.Entity("Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CidadaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_cidadao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int")
                        .HasColumnName("id_denuncia");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_funcionario");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.HasKey("Id");

                    b.HasIndex("CidadaoId");

                    b.HasIndex("DenunciaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("MENSAGEM");
                });

            modelBuilder.Entity("Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadaoId")
                        .HasColumnType("int")
                        .HasColumnName("id_cidadao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("criado_em");

                    b.Property<int?>("DenunciaId")
                        .HasColumnType("int")
                        .HasColumnName("id_denuncia");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit")
                        .HasColumnName("lida");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mensagem");

                    b.HasKey("Id");

                    b.HasIndex("CidadaoId");

                    b.HasIndex("DenunciaId");

                    b.ToTable("NOTIFICACAO");
                });

            modelBuilder.Entity("PrefeituraCidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("PREFEITURA_CIDADE");
                });

            modelBuilder.Entity("Anexo", b =>
                {
                    b.HasOne("Mensagem", "Mensagem")
                        .WithMany("Anexos")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensagem");
                });

            modelBuilder.Entity("Denuncia", b =>
                {
                    b.HasOne("Cidadao", "Cidadao")
                        .WithMany("Denuncias")
                        .HasForeignKey("CidadaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Departamento", "Departamento")
                        .WithMany("Denuncias")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Funcionario", "Funcionario")
                        .WithMany("Denuncias")
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Cidadao");

                    b.Navigation("Departamento");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Departamento", b =>
                {
                    b.HasOne("PrefeituraCidade", "PrefeituraCidade")
                        .WithMany("Departamentos")
                        .HasForeignKey("PrefeituraCidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrefeituraCidade");
                });

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.HasOne("Cidadao", "Cidadao")
                        .WithOne("Funcionario")
                        .HasForeignKey("Funcionario", "CidadaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidadao");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Mensagem", b =>
                {
                    b.HasOne("Cidadao", "Cidadao")
                        .WithMany("Mensagens")
                        .HasForeignKey("CidadaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Denuncia", "Denuncia")
                        .WithMany("Mensagens")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Funcionario", "Funcionario")
                        .WithMany("Mensagens")
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Cidadao");

                    b.Navigation("Denuncia");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Notificacao", b =>
                {
                    b.HasOne("Cidadao", "Cidadao")
                        .WithMany("Notificacoes")
                        .HasForeignKey("CidadaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Denuncia", "Denuncia")
                        .WithMany("Notificacoes")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cidadao");

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("Cidadao", b =>
                {
                    b.Navigation("Denuncias");

                    b.Navigation("Funcionario");

                    b.Navigation("Mensagens");

                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("Denuncia", b =>
                {
                    b.Navigation("Mensagens");

                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("Departamento", b =>
                {
                    b.Navigation("Denuncias");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Navigation("Denuncias");

                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Mensagem", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("PrefeituraCidade", b =>
                {
                    b.Navigation("Departamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
